name: Build FoundryVTT Module

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-foundry-module:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create FoundryVTT module zip
        run: |
          cd foundry-local-rest-api
          zip -r ../foundry-local-rest-api.zip . -x "*.git*" "node_modules/*" "*.DS_Store*"
          cd ..

      - name: Upload FoundryVTT module artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${{ github.ref_name }}" foundry-local-rest-api.zip foundry-local-rest-api/module.json
