name: Build FoundryVTT Module

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-foundry-module:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create FoundryVTT module zip
        run: |
          zip -r mediasoup-vtt.zip . -x "*.git*" "node_modules/*" "*.DS_Store*" "*.github*" "package-lock.json" "rollup.config.js" "eslint.config.js" "src/*" "*.md" "release-please-config.json" ".release-please-manifest.json"

      - name: Upload FoundryVTT module artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${{ github.ref_name }}" mediasoup-vtt.zip module.json
